# Generated by Django 6.0.3 on 2026-03-30 03:28

import django.core.validators
import django.db.models.deletion
import produits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_produit_image_alter_produit_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='type',
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('TRESSE', 'Tresse'), ('NAPPY', 'Nappy'), ('TISSAGE', 'Tissage')], default='TRESSE', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé')], default='CONFIRME', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_rdv',
            field=models.DateField(validators=[produits.models.valider_date_future]),
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cliente', models.CharField(max_length=100)),
                ('note', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='produits.produit')),
            ],
            options={
                'verbose_name_plural': 'Avis',
            },
        ),
    ]
