# Generated by Django 6.0.3 on 2026-03-30 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_remove_produit_type_produit_categorie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avis',
            options={},
        ),
    ]
