# Generated by Django 4.2.30 on 2026-05-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0005_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
