# Generated by Django 4.2.30 on 2026-05-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0007_alter_avis_id_alter_produit_id_alter_reservation_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avis',
            options={'verbose_name': 'Avis Client', 'verbose_name_plural': 'Avis Clients'},
        ),
        migrations.AddField(
            model_name='avis',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avis_photos/'),
        ),
    ]
