# Generated by Django 4.2.30 on 2026-05-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0008_alter_avis_options_avis_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='nom',
        ),
        migrations.AddField(
            model_name='produit',
            name='description_fr',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='nom_en',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='nom_fr',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
