# Generated by Django 4.2.30 on 2026-06-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0009_rename_description_produit_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
